### PR TITLE
fix wrong Try indentation

### LINKED ISSUE #132: Wrong indentation after import `scala.util.Try`
+ Emacs: 25.1.1
+ OS: Archlinux

screenshot from 2017-03-23 11-54-19

Seems `Try` was treat as `keyword`

### PR DESCRIPTION
**Pull request by jilen**
Try to fix #132 

I found wrap the `run-o-p` with `case-fold-search`  `nil` solves my issue.

### CODE REVIEW

**Comment by fommil** [comment]
pro tip: add `&w=1` to the URL when viewing this diff :stuck_out_tongue:

LGTM, @hvesalai ?

**Comment by jilen** [comment]
@fommil  Wait for a minute, I find this may cause some other issues.

**Comment by jilen** [comment]
@fommil  @hvesalai Now it looks good

**Comment by fommil** [comment]
@jilen thanks!

**Pull request merged**
