### PR TITLE
fix #120, align according to forms

### LINKED ISSUE #120: scala-indent:align-forms
I've set `scala-indent:align-forms` to `t` but the indentation is wrong. This is what I get:

``` scala
// (setq scala-indent:align-forms t)

val x = if (foo)
    true
        else
          false
```

The line that has `true` is not indented correctly.

I'm using scala mode version **20160902.525** on Emacs 25.1-rc2 running on Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by hvesalai**

### CODE REVIEW

**Comment by hvesalai** [comment]
This needs some testing. It's a clear bug fix but still changes the handling of many things

**Comment by hvesalai** [comment]
with `scala-indent:align-format` `t`

```scala
val y = if (x)
          foo
        else
          bar
```

and else

```
val y = if (x)
  foo
else
  bar
```

**Comment by fommil** [comment]
I like that example. I tend to use scalariform (or scalafmt) as part of my build so unfortunately even if this is prettier than scalariform it won't impact my checked in code... @olafurpg do you have any cool features for this kind of alignment?

**Comment by olafurpg** [comment]
scalafmt would reformat that as

```scala
val y =
  if (x)
    foo
  else
    bar
```

Scalafmt has lots of alignment goodies but not for `if`/`else`.

**Comment by hvesalai** [comment]
scala-mode doesn't format the code other than indent it. So with the newline between `=` and `if` it would do the same as your formatter.

**Comment by fommil** [comment]
cool, it's good to catch the discrepencies. Once I get used to the auto formatter, I tend to write code that doesn't need to be auto formatted (much)

**Comment by hvesalai** [comment]
@nloyola heads up, please give this a spin!

**Comment by nloyola** [comment]
Thanks @hvesalai! It works for me.

**Pull request merged**
